# Generated by Django 5.2.1 on 2025-05-18 06:45

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        help_text="Search vector for full-text search", null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        help_text="Associated product",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_index",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "search index",
                "verbose_name_plural": "search indexes",
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="search_vector_idx"
                    ),
                    models.Index(fields=["product"], name="search_product_idx"),
                ],
            },
        ),
    ]
