# Generated by Django 5.2.1 on 2025-05-18 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(help_text="Start date of the report period"),
                ),
                (
                    "end_date",
                    models.DateTimeField(help_text="End date of the report period"),
                ),
                (
                    "total_orders",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of orders"
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total revenue generated",
                        max_digits=14,
                    ),
                ),
                (
                    "average_order_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Average order value",
                        max_digits=12,
                    ),
                ),
                (
                    "top_products",
                    models.JSONField(
                        default=list, help_text="List of top-selling products"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "sales report",
                "verbose_name_plural": "sales reports",
                "indexes": [
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="analytics_s_start_d_f9aabf_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="analytics_s_created_620e79_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("view", "Product View"),
                            ("search", "Search Query"),
                            ("order", "Order Placement"),
                            ("coupon", "Coupon Usage"),
                        ],
                        help_text="Type of activity",
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Additional details (e.g., product ID, search query)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the activity",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user activity",
                "verbose_name_plural": "user activities",
                "indexes": [
                    models.Index(
                        fields=["user", "activity_type"],
                        name="analytics_u_user_id_266824_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="analytics_u_created_775113_idx"
                    ),
                ],
            },
        ),
    ]
