# Generated by Django 5.2.1 on 2025-05-16 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("VIEW", "View"),
                            ("SYSTEM", "System"),
                        ],
                        help_text="Type of action performed.",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCESS", "Success"), ("FAILED", "Failed")],
                        default="SUCCESS",
                        help_text="Status of the action.",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("LOW", "Low"), ("MED", "Medium"), ("HIGH", "High")],
                        default="LOW",
                        help_text="Priority level of the action.",
                        max_length=10,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the client.", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="User agent of the client (browser/server details).",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="ID of the object affected.", null=True
                    ),
                ),
                (
                    "object_repr",
                    models.TextField(
                        blank=True,
                        help_text="String representation of the affected object.",
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Changes made (before and after) in JSON format.",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata (e.g., request URL, method).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if the action failed."
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Model associated with the action.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action, if applicable.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "audit log",
                "verbose_name_plural": "audit logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="audit_log_a_user_id_6ee8ec_idx",
                    ),
                    models.Index(
                        fields=["action_type"], name="audit_log_a_action__b48e9f_idx"
                    ),
                    models.Index(
                        fields=["status"], name="audit_log_a_status_b50950_idx"
                    ),
                    models.Index(
                        fields=["priority"], name="audit_log_a_priorit_cdd9ea_idx"
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="audit_log_a_content_bf31bf_idx",
                    ),
                    models.Index(
                        fields=["ip_address"], name="audit_log_a_ip_addr_867599_idx"
                    ),
                ],
            },
        ),
    ]
